disabled_rules:
- force_cast
- line_length
- trailing_whitespace
- function_parameter_count
- function_body_length
- identifier_name
- nesting
- orphaned_doc_comment
- shorthand_operator
- legacy_constructor
- redundant_optional_initialization
- unused_closure_parameter
- discouraged_direct_init
- file_length
- cyclomatic_complexity
- type_body_length

excluded:
- Sopetit-iOS/Application/SceneDelegate.swift
- Sopetit-iOS/Application/AppDelegate.swift
